language: php

sudo: false

git:
  depth: 1

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=4.4.*
    - php: 7.2
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*

cache:
  directories:
    - $HOME/.composer

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - echo memory_limit = -1 >> $INI_FILE
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer install

script: php tests.php
